import{execFile}from'node:child_process';
import { guardedArgv, sanitizeChildEnv, writeSandboxProfile } from './spawn-shell';import{promisify}from'node:util';
import type{ExecutionAdapter,ExecutionContext,ExecutionEvents,ExecutionRunResult}from'../task-engine/executor';
import{agentRunResultSchema}from'./result-schema';import{tryParseJSON}from'../../shared/utils';import{AppError,ErrorCode}from'../../shared/errors';
import{resolveCliEnvironment}from'./cli-environment';
import{startAntigravityPermissionBridge}from'./antigravity-permission-bridge';
const execFileAsync=promisify(execFile);
type Runner=(binary:string,args:string[],options:{cwd:string;env:NodeJS.ProcessEnv;signal?:AbortSignal;timeout:number})=>Promise<{exitCode:number;stdout:string;stderr:string}>;
const defaultRunner:Runner=async(binary,args,options)=>{try{const result=await execFileAsync(binary,args,{...options,maxBuffer:16*1024*1024});return{exitCode:0,stdout:result.stdout,stderr:result.stderr};}catch(error:any){return{exitCode:typeof error.code==='number'?error.code:1,stdout:error.stdout??'',stderr:error.stderr??error.message};}};
export class AntigravityCliAdapter implements ExecutionAdapter{constructor(private options:{runner?:Runner}={}){}async run(ctx:ExecutionContext,events?:ExecutionEvents):Promise<ExecutionRunResult>{const binary=ctx.agentExecutor?.binaryPath??'agy';const prompt=[ctx.systemPrompt,'# 当前 Task 工作包',JSON.stringify(ctx.inputPacket,null,2),'最终仅返回 AgentRunResult JSON；不得使用 Markdown 代码块。'].join('\n\n');const args=['--print',prompt,'--print-timeout',`${Math.ceil((ctx.agentExecutor?.timeoutMs??600_000)/1000)}s`,'--sandbox'];for(const root of ctx.permissionPolicy?.allowedRoots??[]){if(root!==ctx.workingDir)args.push('--add-dir',root);}if(ctx.sessionIdHint)args.push('--conversation',ctx.sessionIdHint);const bridge=this.options.runner?{close:async()=>{}}:await startAntigravityPermissionBridge(ctx.workingDir,ctx.permissionGuard);
// H9a 统一执行壳：seatbelt 文件写围栏（allowedRoots 一并放行——antigravity --add-dir 需要写授权目录）+ env 清洗。
const profilePath=writeSandboxProfile({writableRoots:[ctx.workingDir,...(ctx.permissionPolicy?.allowedRoots??[])],profileDir:ctx.runTempDir,id:`antigravity_${ctx.task.id}`});
const argv=guardedArgv(binary,args,profilePath);try{// H9a 统一执行壳：seatbelt 文件写围栏（allowedRoots 一并放行——antigravity --add-dir 需要写授权目录）+ env 清洗。
    const profilePath=writeSandboxProfile({writableRoots:[ctx.workingDir,...(ctx.permissionPolicy?.allowedRoots??[])],profileDir:ctx.runTempDir,id:`antigravity_${ctx.task.id}`});
    const argv=guardedArgv(binary,args,profilePath);
    const result=await(this.options.runner??defaultRunner)(argv[0]!,argv.slice(1),{cwd:ctx.workingDir,env:sanitizeChildEnv(await resolveCliEnvironment()),signal:ctx.signal,timeout:ctx.agentExecutor?.timeoutMs??600_000});events?.onOutput?.(result.stdout);if(result.exitCode!==0)throw new AppError(ErrorCode.INTERNAL,`Antigravity CLI 执行失败: ${(result.stderr||result.stdout).slice(0,2000)}`);const raw=tryParseJSON(result.stdout) as any;const parsed=agentRunResultSchema.safeParse(raw);if(!parsed.success)throw new AppError(ErrorCode.VALIDATION,'Antigravity CLI 未返回有效的 AgentRunResult');return{...parsed.data,_sessionIdHint:typeof raw?.conversationId==='string'?raw.conversationId:ctx.sessionIdHint};}finally{if(profilePath){try{(await import('node:fs')).unlinkSync(profilePath);}catch{}}await bridge.close();}}}
