import {execFile} from 'node:child_process';import{promisify}from'node:util';import type{ExecutionAdapter,ExecutionContext,ExecutionEvents,ExecutionRunResult}from'../task-engine/executor';import{agentRunResultSchema}from'./result-schema';import{tryParseJSON}from'../../shared/utils';import{AppError,ErrorCode}from'../../shared/errors';
import { CLI_UPGRADE_HINT } from './spawn-errors';
import { commonCliWritableRoots, guardedArgv, sanitizeChildEnv, writeSandboxProfile } from './spawn-shell';
const execFileAsync=promisify(execFile);type Runner=(binary:string,args:string[],options:{cwd:string;env:NodeJS.ProcessEnv;signal?:AbortSignal;timeout:number;shell:false})=>Promise<{exitCode:number;stdout:string;stderr:string}>;const defaultRunner:Runner=async(binary,args,options)=>{try{const result=await execFileAsync(binary,args,{...options,maxBuffer:16*1024*1024});return{exitCode:0,stdout:result.stdout,stderr:result.stderr};}catch(error:any){return{exitCode:1,stdout:error.stdout??'',stderr:error.stderr??error.message};}};
export class CustomCliAdapter implements ExecutionAdapter{constructor(private options:{runner?:Runner}={}){}async run(ctx:ExecutionContext,events?:ExecutionEvents):Promise<ExecutionRunResult>{const binary=ctx.agentExecutor?.binaryPath;if(!binary)throw new AppError(ErrorCode.VALIDATION,'自定义 CLI 未配置可执行文件');const prompt=[ctx.systemPrompt,JSON.stringify(ctx.inputPacket,null,2)].join('\n\n');const templates=ctx.agentExecutor?.customArgs??['{prompt}'];const values:Record<string,string>={'{prompt}':prompt,'{cwd}':ctx.workingDir,'{taskId}':ctx.task.id,'{sessionId}':ctx.sessionIdHint??''};const args=templates.map((item)=>values[item]??item);// H9a 统一执行壳：env 全量直通洞堵上（清洗后传入）+ seatbelt 文件写围栏（worktree 外写被 OS 拒）。
    const profilePath=writeSandboxProfile({writableRoots:[ctx.workingDir,...commonCliWritableRoots()],profileDir:ctx.runTempDir,id:`custom_${ctx.task.id}`});
    const argv=guardedArgv(binary,args,profilePath);
    try{
    const result=await(this.options.runner??defaultRunner)(argv[0]!,argv.slice(1),{cwd:ctx.workingDir,env:sanitizeChildEnv(process.env),signal:ctx.signal,timeout:ctx.agentExecutor?.timeoutMs??600_000,shell:false});events?.onOutput?.(result.stdout);if(result.exitCode!==0)throw new AppError(ErrorCode.INTERNAL,`自定义 CLI 执行失败: ${result.stderr.slice(0,2000)}${CLI_UPGRADE_HINT}`);const parsed=agentRunResultSchema.safeParse(tryParseJSON(result.stdout));if(!parsed.success)throw new AppError(ErrorCode.VALIDATION,'自定义 CLI 未返回 AgentRunResult JSON');return parsed.data;}finally{if(profilePath){try{(await import('node:fs')).unlinkSync(profilePath);}catch{}}}}}
