import{execFile}from'node:child_process';import{promisify}from'node:util';import{mkdtempSync,readdirSync,rmSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';
import type{DB}from'../db/client';import{shortId}from'../../shared/utils';import{getExecutorProfile}from'./executor-profile';import{getExecutorManifest,type ExecutorManifest}from'../executors/manifests';
const execFileAsync=promisify(execFile);const OK='MUSTER_CONNECTION_OK';
export type ProbeClassification='not_found'|'version_failed'|'authentication_failed'|'model_failed'|'network_failed'|'permission_bridge_failed'|'timeout'|'invalid_output'|'mutated_workspace'|'failed';
export interface ConnectionProbe{id:string;executorProfileId:string;cacheKey:string;status:'queued'|'testing'|'connected'|'failed';classification:ProbeClassification|null;version:string|null;stdout:string;stderr:string;durationMs:number;startedAt:string|null;completedAt:string|null;createdAt:string}
type Row={id:string;executor_profile_id:string;cache_key:string;status:ConnectionProbe['status'];classification:ProbeClassification|null;version:string|null;stdout:string;stderr:string;duration_ms:number;started_at:string|null;completed_at:string|null;created_at:string};
const fromRow=(r:Row):ConnectionProbe=>({id:r.id,executorProfileId:r.executor_profile_id,cacheKey:r.cache_key,status:r.status,classification:r.classification,version:r.version,stdout:r.stdout,stderr:r.stderr,durationMs:r.duration_ms,startedAt:r.started_at,completedAt:r.completed_at,createdAt:r.created_at});
export interface ProbeRuntime{run:(input:{binary:string;manifest:Readonly<ExecutorManifest>;cwd:string;prompt:string;timeoutMs:number})=>Promise<{exitCode:number;stdout:string;stderr:string;durationMs:number;filesAfter:string[]}>}
const defaultRuntime:ProbeRuntime={run:async input=>{const before=Date.now();const args=probeArgs(input.manifest.id,input.prompt);try{const result=await execFileAsync(input.binary,args,{cwd:input.cwd,env:{...process.env},timeout:input.timeoutMs,maxBuffer:4*1024*1024});return{exitCode:0,stdout:result.stdout,stderr:result.stderr,durationMs:Date.now()-before,filesAfter:readdirSync(input.cwd)};}catch(error:any){return{exitCode:typeof error.code==='number'?error.code:1,stdout:error.stdout??'',stderr:error.stderr??error.message,durationMs:Date.now()-before,filesAfter:readdirSync(input.cwd)};}}};
function probeArgs(id:string,prompt:string):string[]{if(id==='codex-cli')return['exec','-s','read-only','-a','never',prompt];if(id==='claude-code-cli')return['-p',prompt,'--output-format','text','--tools',''];if(id==='antigravity-cli')return['--print',prompt,'--sandbox','--print-timeout','60s'];if(id==='gemini-cli')return['-p',prompt,'--sandbox'];return[];}
export function getConnectionProbe(db:DB,id:string):ConnectionProbe{const row=db.prepare('SELECT * FROM connection_probe WHERE id=?').get(id)as Row|undefined;if(!row)throw new Error(`connection probe not found: ${id}`);return fromRow(row);}
export async function runConnectionProbe(db:DB,input:{profileId:string;force:boolean;runtime?:ProbeRuntime;now?:Date;probeId?:string}):Promise<ConnectionProbe>{const profile=getExecutorProfile(db,input.profileId);const manifest=getExecutorManifest(profile.manifestId);const binary=String(profile.config.binaryPath??'');const version=profile.install.detectedVersion??null;const cacheKey=JSON.stringify([binary,version,profile.config.model??null]);const now=input.now??new Date();if(!input.force){const cached=db.prepare("SELECT * FROM connection_probe WHERE executor_profile_id=? AND cache_key=? AND status='connected' AND completed_at>=? ORDER BY completed_at DESC LIMIT 1").get(profile.id,cacheKey,new Date(now.getTime()-86_400_000).toISOString())as Row|undefined;if(cached)return fromRow(cached);}const id=input.probeId??shortId('probe_');const created=now.toISOString();db.prepare("INSERT OR IGNORE INTO connection_probe (id,executor_profile_id,cache_key,status,version,created_at) VALUES (?,?,?,'queued',?,?)").run(id,profile.id,cacheKey,version,created);db.prepare("UPDATE connection_probe SET status='testing',started_at=? WHERE id=?").run(created,id);const cwd=mkdtempSync(join(tmpdir(),'muster-probe-'));try{const result=await(input.runtime??defaultRuntime).run({binary,manifest,cwd,prompt:`只回复 ${OK}，不要调用工具，不要读取或修改文件。`,timeoutMs:60_000});const cleanOut=redact(result.stdout),cleanErr=redact(result.stderr);const classification=result.exitCode===0?(result.filesAfter.length?'mutated_workspace':cleanOut.includes(OK)?null:'invalid_output'):classify(`${cleanOut}\n${cleanErr}`);const status=classification?'failed':'connected';db.prepare('UPDATE connection_probe SET status=?,classification=?,stdout=?,stderr=?,duration_ms=?,completed_at=? WHERE id=?').run(status,classification,cleanOut,cleanErr,result.durationMs,now.toISOString(),id);return getConnectionProbe(db,id);}finally{rmSync(cwd,{recursive:true,force:true});}}
export function startConnectionProbe(db:DB,input:{profileId:string;force:boolean;runtime?:ProbeRuntime}):ConnectionProbe{const profile=getExecutorProfile(db,input.profileId);const key=JSON.stringify([profile.config.binaryPath??'',profile.install.detectedVersion??null,profile.config.model??null]);const id=shortId('probe_'),now=new Date().toISOString();db.prepare("INSERT INTO connection_probe (id,executor_profile_id,cache_key,status,version,created_at) VALUES (?,?,?,'queued',?,?)").run(id,profile.id,key,profile.install.detectedVersion??null,now);queueMicrotask(()=>{void runConnectionProbe(db,{...input,probeId:id}).catch(error=>{if(db.open)db.prepare("UPDATE connection_probe SET status='failed',classification='failed',stderr=?,completed_at=? WHERE id=?").run(redact(String(error)),new Date().toISOString(),id);});});return getConnectionProbe(db,id);}
function classify(text:string):ProbeClassification{const value=text.toLowerCase();if(/auth|login|401|unauthorized|not logged/.test(value))return'authentication_failed';if(/model.*(not found|unsupported|access)|invalid.*model/.test(value))return'model_failed';if(/network|dns|econn|tls|proxy|retry/.test(value))return'network_failed';if(/timeout|timed out/.test(value))return'timeout';return'failed';}
export function redact(text:string):string{return text.replace(/(authorization\s*:\s*bearer\s+)[^\s]+/gi,'$1[REDACTED]').replace(/((?:api[_-]?key|token|secret)\s*[=:]\s*)[^\s]+/gi,'$1[REDACTED]');}
