import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { chmodSync, existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import type { DB } from '../db/client';
import { AppError, ErrorCode } from '../../shared/errors';
import { nowIso, shortId } from '../../shared/utils';
import { getExecutorManifest } from '../executors/manifests';

const execFileAsync = promisify(execFile);
export interface CommandResult { stdout:string; stderr:string; exitCode:number }
export interface InstallRuntime { run:(command:string,args:string[])=>Promise<CommandResult>; which?:(command:string)=>Promise<string|null> }
export interface ExecutorInstall { id:string; manifestId:string; channel:string; platform:string; arch:string; packageName:string; targetDir:string; binaryPath:string|null; officialSource:string; confirmationToken:string; status:'planned'|'installing'|'installed'|'failed'|'rolled-back'; version:string|null; error:string|null; createdAt:string; updatedAt:string }
type Row={id:string;manifest_id:string;channel:string;platform:string;arch:string;package_name:string;target_dir:string;binary_path:string|null;official_source:string;confirmation_token:string;status:ExecutorInstall['status'];version:string|null;error:string|null;created_at:string;updated_at:string};
function fromRow(r:Row):ExecutorInstall{return{id:r.id,manifestId:r.manifest_id,channel:r.channel,platform:r.platform,arch:r.arch,packageName:r.package_name,targetDir:r.target_dir,binaryPath:r.binary_path,officialSource:r.official_source,confirmationToken:r.confirmation_token,status:r.status,version:r.version,error:r.error,createdAt:r.created_at,updatedAt:r.updated_at};}
export function getExecutorInstall(db:DB,id:string):ExecutorInstall{const row=db.prepare('SELECT * FROM executor_install WHERE id=?').get(id) as Row|undefined;if(!row)throw new AppError(ErrorCode.NOT_FOUND,`安装计划不存在: ${id}`);return fromRow(row);}
export function createExecutorInstallPlan(db:DB,input:{manifestId:string;channel:'stable'|'latest'|string;musterHome:string;platform?:string;arch?:string}):ExecutorInstall{const manifest=getExecutorManifest(input.manifestId);if(!manifest.managedInstall)throw new AppError(ErrorCode.VALIDATION,'该执行器不需要或不支持托管安装');const platform=input.platform??process.platform;const arch=input.arch??process.arch;if(!manifest.platforms.includes(platform))throw new AppError(ErrorCode.VALIDATION,`不支持当前平台: ${platform}`);const id=shortId('install_');const token=shortId('install_');const now=nowIso();const targetDir=join(input.musterHome,'runtimes',manifest.id,input.channel);db.prepare(`INSERT INTO executor_install (id,manifest_id,channel,platform,arch,package_name,target_dir,official_source,confirmation_token,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,'planned',?,?)`).run(id,manifest.id,input.channel,platform,arch,manifest.managedInstall.packageName,targetDir,manifest.officialSource,token,now,now);return getExecutorInstall(db,id);}
function bundledNpmCli():string{const require=createRequire(import.meta.url);return join(dirname(require.resolve('npm/package.json')),'bin','npm-cli.js');}
const defaultRuntime:InstallRuntime={run:async(command,args)=>{try{const result=await execFileAsync(command,args,{timeout:10*60_000,maxBuffer:4*1024*1024});return{stdout:result.stdout,stderr:result.stderr,exitCode:0};}catch(error:any){return{stdout:error.stdout??'',stderr:error.stderr??error.message,exitCode:error.code??1};}},which:async(command)=>{try{const result=await execFileAsync('/usr/bin/which',[command],{timeout:3000});return result.stdout.trim()||null;}catch{return null;}}};
export async function executeExecutorInstallPlan(db:DB,id:string,confirmationToken:string,runtime:InstallRuntime=defaultRuntime):Promise<ExecutorInstall>{const plan=getExecutorInstall(db,id);if(plan.status!=='planned'&&plan.status!=='failed')throw new AppError(ErrorCode.CONFLICT,'安装计划状态不允许执行');if(confirmationToken!==plan.confirmationToken)throw new AppError(ErrorCode.VALIDATION,'安装确认令牌不匹配');const manifest=getExecutorManifest(plan.manifestId);const recipe=manifest.managedInstall!;const tag=plan.channel==='stable'?recipe.stableTag:plan.channel==='latest'?recipe.latestTag:plan.channel;mkdirSync(plan.targetDir,{recursive:true});db.prepare("UPDATE executor_install SET status='installing',error=NULL,updated_at=? WHERE id=?").run(nowIso(),id);const args=[bundledNpmCli(),'install','--prefix',plan.targetDir,`${recipe.packageName}@${tag}`,'--omit=dev','--no-audit','--no-fund'];const result=await runtime.run(process.execPath,args);const binaryPath=join(plan.targetDir,'node_modules','.bin',process.platform==='win32'?`${recipe.binaryName}.cmd`:recipe.binaryName);if(result.exitCode!==0||!existsSync(binaryPath)){const error=(result.stderr||`安装后未找到 ${binaryPath}`).slice(0,4000);db.prepare("UPDATE executor_install SET status='failed',error=?,updated_at=? WHERE id=?").run(error,nowIso(),id);throw new AppError(ErrorCode.INTERNAL,`执行器安装失败: ${error}`);}const verify=await runtime.run(binaryPath,['--version']);const version=(verify.stdout||verify.stderr).trim().split(/\s+/).at(-1)??'unknown';db.prepare("UPDATE executor_install SET status='installed',binary_path=?,version=?,error=NULL,updated_at=? WHERE id=?").run(binaryPath,version,nowIso(),id);return getExecutorInstall(db,id);}
export async function detectExecutor(manifestId:string,runtime:InstallRuntime=defaultRuntime):Promise<{found:boolean;path:string|null;version:string|null;managed:false}>{const manifest=getExecutorManifest(manifestId);if(!manifest.detection)return{found:false,path:null,version:null,managed:false};const path=await runtime.which?.(manifest.detection.command)??null;if(!path)return{found:false,path:null,version:null,managed:false};const result=await runtime.run(path,manifest.detection.args);return{found:result.exitCode===0,path,version:(result.stdout||result.stderr).trim()||null,managed:false};}
export function rollbackExecutorInstall(db:DB,id:string):ExecutorInstall{const install=getExecutorInstall(db,id);if(install.status==='installing')throw new AppError(ErrorCode.CONFLICT,'安装进行中不能回滚');rmSync(install.targetDir,{recursive:true,force:true});db.prepare("UPDATE executor_install SET status='rolled-back',binary_path=NULL,updated_at=? WHERE id=?").run(nowIso(),id);return getExecutorInstall(db,id);}
export async function launchExecutorLogin(db:DB,id:string,runtime:InstallRuntime=defaultRuntime):Promise<{launched:true;launcherPath:string}>{const install=getExecutorInstall(db,id);if(install.status!=='installed'||!install.binaryPath)throw new AppError(ErrorCode.CONFLICT,'执行器尚未安装完成');if(process.platform!=='darwin')throw new AppError(ErrorCode.VALIDATION,'当前登录启动器仅支持 macOS');const args=install.manifestId==='codex-cli'?['login']:install.manifestId==='claude-code-cli'?['auth','login']:[];mkdirSync(install.targetDir,{recursive:true});const launcherPath=join(install.targetDir,'登录.command');const line=[install.binaryPath,...args].map(shellQuote).join(' ');writeFileSync(launcherPath,`#!/bin/zsh\n${line}\n`,{mode:0o700});chmodSync(launcherPath,0o700);const result=await runtime.run('/usr/bin/open',['-a','Terminal',launcherPath]);if(result.exitCode!==0)throw new AppError(ErrorCode.INTERNAL,`无法打开登录窗口: ${result.stderr}`);return{launched:true,launcherPath};}
function shellQuote(value:string):string{return `'${value.replace(/'/g,"'\\''")}'`;}
