import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import type { DB } from '../db/client';
import { AppError, ErrorCode } from '../../shared/errors';
import { getExecutorManifest } from '../executors/manifests';
import { createExecutorProfile, getExecutorProfile, listExecutorProfiles, type ExecutorProfile } from './executor-profile';

const execFileAsync=promisify(execFile);
export interface DiscoveryRuntime { run:(command:string,args:string[])=>Promise<{stdout:string;stderr:string;exitCode:number}>;which:(command:string)=>Promise<string|null> }
const defaultRuntime:DiscoveryRuntime={run:async(command,args)=>{try{const result=await execFileAsync(command,args,{timeout:5000});return{stdout:result.stdout,stderr:result.stderr,exitCode:0};}catch(error:any){return{stdout:error.stdout??'',stderr:error.stderr??error.message,exitCode:1};}},which:async(command)=>{try{const result=await execFileAsync('/usr/bin/which',[command],{timeout:3000});return result.stdout.trim()||null;}catch{return null;}}};
export async function detectSystemExecutor(manifestId:string,runtime:DiscoveryRuntime=defaultRuntime):Promise<{found:boolean;path:string|null;version:string|null;managed:false}>{const manifest=getExecutorManifest(manifestId);if(!manifest.detection)return{found:false,path:null,version:null,managed:false};const path=await runtime.which(manifest.detection.command);if(!path)return{found:false,path:null,version:null,managed:false};const result=await runtime.run(path,manifest.detection.args);return{found:result.exitCode===0,path,version:(result.stdout||result.stderr).trim()||null,managed:false};}
export async function bindDetectedSystemExecutor(db:DB,manifestId:string,runtime:DiscoveryRuntime=defaultRuntime):Promise<ExecutorProfile>{const manifest=getExecutorManifest(manifestId);const detection=await detectSystemExecutor(manifestId,runtime);if(!detection.found||!detection.path)throw new AppError(ErrorCode.NOT_FOUND,`${manifest.displayName} 尚未安装，请先按官方说明完成安装`);const existing=listExecutorProfiles(db).find((profile)=>profile.manifestId===manifestId&&profile.config.binaryPath===detection.path);if(existing)return existing;return createExecutorProfile(db,{name:`${manifest.displayName} (${detection.version??'系统安装'})`,manifestId,config:{binaryPath:detection.path,provider:providerForManifest(manifestId)},install:{managed:false,source:'system',detectedVersion:detection.version}});}
export async function testExecutorProfileConnection(db:DB,profileId:string,runtime:DiscoveryRuntime=defaultRuntime):Promise<{version:{success:boolean;output:string};authentication:{supported:boolean;success:boolean;output:string}}> {const profile=getExecutorProfile(db,profileId);const manifest=getExecutorManifest(profile.manifestId);const binary=profile.config.binaryPath;if(typeof binary!=='string')throw new AppError(ErrorCode.VALIDATION,'执行器档案没有 CLI 路径');const version=await runtime.run(binary,manifest.detection?.args??['--version']);const authArgs=profile.manifestId==='codex-cli'?['login','status']:profile.manifestId==='claude-code-cli'?['auth','status','--text']:null;if(!authArgs)return{version:{success:version.exitCode===0,output:(version.stdout||version.stderr).trim()},authentication:{supported:false,success:false,output:'请运行官方登录命令后执行一次 Task 验证'}};const auth=await runtime.run(binary,authArgs);return{version:{success:version.exitCode===0,output:(version.stdout||version.stderr).trim()},authentication:{supported:true,success:auth.exitCode===0,output:(auth.stdout||auth.stderr).trim()}};}
function providerForManifest(id:string):string{return id==='claude-code-cli'?'claude-cli':id==='antigravity-cli'?'antigravity-cli':id==='openai-compatible-api'?'openai':id==='gemini-api'?'gemini':id;}
