import { resolve, extname, dirname } from 'node:path';
import type { DB } from '../db/client';
import { AppError, ErrorCode } from '../../shared/errors';
import { resumeTaskAfterApproval } from './task';
import { nowIso, shortId } from '../../shared/utils';

export type ApprovalStrategy = 'ask-always' | 'ask-by-rule' | 'no-approval' | 'deny';
export type PermissionScope = 'task' | 'project' | 'workspace' | 'selected-directories' | 'device';
export type PermissionDecision = 'allow' | 'deny' | 'approval-required';
export const HIGH_RISK_ACTIONS = new Set(['delete-outside-project','system-install','credential-access','git-push','deploy','external-message','account-action','paid-action']);

export interface PermissionPolicy { id: string; name: string; approvalStrategy: ApprovalStrategy; scope: PermissionScope; selectedDirectories: string[]; createdAt: string; updatedAt: string }
export interface PermissionRequest { action: string; command?: string; path?: string; taskRoot: string; projectRoot: string; workspaceRoot: string; employeeId?: string; companyId?: string; projectId?: string; taskId?: string; network?: boolean; subprocess?: boolean }
export interface PermissionRuleInput { effect: 'allow'|'deny'; action?: string; commandPattern?: string; pathPrefix?: string; fileExtension?: string; employeeId?: string; companyId?: string; projectId?: string; taskId?: string; network?: boolean; subprocess?: boolean; expiresAt?: string }

type PolicyRow = { id:string; name:string; approval_strategy:ApprovalStrategy; scope:PermissionScope; selected_directories_json:string; created_at:string; updated_at:string };
type RuleRow = { id:string; policy_id:string; effect:'allow'|'deny'; action:string|null; command_pattern:string|null; path_prefix:string|null; file_extension:string|null; employee_id:string|null; company_id:string|null; project_id:string|null; task_id:string|null; network:number|null; subprocess:number|null; expires_at:string|null };

function fromRow(row: PolicyRow): PermissionPolicy { return { id:row.id, name:row.name, approvalStrategy:row.approval_strategy, scope:row.scope, selectedDirectories:JSON.parse(row.selected_directories_json), createdAt:row.created_at, updatedAt:row.updated_at }; }
export function createPermissionPolicy(db:DB,input:{name:string;approvalStrategy:ApprovalStrategy;scope:PermissionScope;selectedDirectories?:string[]}):PermissionPolicy { const now=nowIso(); const id=shortId('pp_'); db.prepare('INSERT INTO permission_policy (id,name,approval_strategy,scope,selected_directories_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?)').run(id,input.name.trim(),input.approvalStrategy,input.scope,JSON.stringify(input.selectedDirectories??[]),now,now); return getPermissionPolicy(db,id); }
export function getPermissionPolicy(db:DB,id:string):PermissionPolicy { const row=db.prepare('SELECT * FROM permission_policy WHERE id=?').get(id) as PolicyRow|undefined; if(!row) throw new AppError(ErrorCode.NOT_FOUND,`权限策略不存在: ${id}`); return fromRow(row); }
export function listPermissionPolicies(db:DB):PermissionPolicy[] { return (db.prepare('SELECT * FROM permission_policy ORDER BY created_at,id').all() as PolicyRow[]).map(fromRow); }
export function listPendingApprovals(db:DB):Record<string,unknown>[] { return db.prepare("SELECT * FROM permission_approval WHERE status='pending' ORDER BY created_at").all() as Record<string,unknown>[]; }
export function getEmployeePermissionPolicy(db:DB,employeeId:string):PermissionPolicy|null { const row=db.prepare('SELECT permission_policy_id FROM company_employee WHERE id=?').get(employeeId) as {permission_policy_id:string|null}|undefined;if(!row)throw new AppError(ErrorCode.NOT_FOUND,`公司员工不存在: ${employeeId}`);return row.permission_policy_id?getPermissionPolicy(db,row.permission_policy_id):null; }
export function bindEmployeePermissionPolicy(db:DB,employeeId:string,policyId:string):void { getPermissionPolicy(db,policyId); const employment=db.prepare('SELECT c.state FROM company_employee ce JOIN company c ON c.id=ce.company_id WHERE ce.id=?').get(employeeId) as {state:string}|undefined; if(!employment)throw new AppError(ErrorCode.NOT_FOUND,`公司员工不存在: ${employeeId}`);if(employment.state!=='off')throw new AppError(ErrorCode.CONFLICT,'公司下班后才能修改员工权限'); const result=db.prepare('UPDATE company_employee SET permission_policy_id=?,updated_at=? WHERE id=?').run(policyId,nowIso(),employeeId); if(result.changes!==1) throw new AppError(ErrorCode.NOT_FOUND,`公司员工不存在: ${employeeId}`); }

function inside(root:string,path:string):boolean { const a=resolve(root); const b=resolve(path); return a===b||b.startsWith(`${a}/`); }
function inScope(policy:PermissionPolicy,request:PermissionRequest):boolean { if(!request.path) return true; if(policy.scope==='device') return true; if(policy.scope==='task') return inside(request.taskRoot,request.path); if(policy.scope==='project') return inside(request.projectRoot,request.path); if(policy.scope==='workspace') return inside(request.workspaceRoot,request.path); return policy.selectedDirectories.some((root)=>inside(root,request.path!)); }
function matches(rule:RuleRow,request:PermissionRequest):boolean { if(rule.expires_at&&rule.expires_at<=nowIso()) return false; if(rule.action&&rule.action!==request.action) return false; if(rule.command_pattern&&(!request.command||!new RegExp(rule.command_pattern).test(request.command))) return false; if(rule.path_prefix&&(!request.path||!inside(rule.path_prefix,request.path))) return false; if(rule.file_extension&&(!request.path||extname(request.path)!==rule.file_extension)) return false; if(rule.employee_id&&rule.employee_id!==request.employeeId) return false; if(rule.company_id&&rule.company_id!==request.companyId) return false; if(rule.project_id&&rule.project_id!==request.projectId) return false; if(rule.task_id&&rule.task_id!==request.taskId) return false; if(rule.network!==null&&Boolean(rule.network)!==Boolean(request.network)) return false; if(rule.subprocess!==null&&Boolean(rule.subprocess)!==Boolean(request.subprocess)) return false; return true; }

export function evaluatePermission(db:DB,policyId:string,request:PermissionRequest):{decision:PermissionDecision;reason:string;ruleId?:string} { const policy=getPermissionPolicy(db,policyId); const rules=db.prepare('SELECT * FROM permission_rule WHERE policy_id=? ORDER BY created_at DESC').all(policyId) as RuleRow[]; const rule=rules.find((item)=>matches(item,request)); if(rule) return {decision:rule.effect,reason:'matched-rule',ruleId:rule.id}; if(policy.approvalStrategy==='deny') return {decision:'deny',reason:'policy-deny'}; if(HIGH_RISK_ACTIONS.has(request.action)) return {decision:'approval-required',reason:'high-risk'}; if(!inScope(policy,request)) return {decision:'approval-required',reason:'outside-scope'}; if(policy.approvalStrategy==='no-approval') return {decision:'allow',reason:'within-scope'}; return {decision:'approval-required',reason:policy.approvalStrategy}; }

export function savePermissionRule(db:DB,policyId:string,input:PermissionRuleInput):string { getPermissionPolicy(db,policyId); if(input.commandPattern) { try { new RegExp(input.commandPattern); } catch { throw new AppError(ErrorCode.VALIDATION,'命令规则不是有效正则表达式'); } } const id=shortId('rule_'); db.prepare(`INSERT INTO permission_rule (id,policy_id,effect,action,command_pattern,path_prefix,file_extension,employee_id,company_id,project_id,task_id,network,subprocess,expires_at,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,policyId,input.effect,input.action??null,input.commandPattern??null,input.pathPrefix??null,input.fileExtension??null,input.employeeId??null,input.companyId??null,input.projectId??null,input.taskId??null,input.network===undefined?null:Number(input.network),input.subprocess===undefined?null:Number(input.subprocess),input.expiresAt??null,nowIso()); return id; }

export function requestApproval(db:DB,input:{policyId:string;employeeId:string;taskId:string;action:string;command?:string;path?:string;risk?:string}):{id:string;status:'pending'} { getPermissionPolicy(db,input.policyId); const id=shortId('approval_'); db.prepare(`INSERT INTO permission_approval (id,policy_id,employee_id,task_id,action,command,path,risk,status,created_at) VALUES (?,?,?,?,?,?,?,?, 'pending',?)`).run(id,input.policyId,input.employeeId,input.taskId,input.action,input.command??null,input.path??null,input.risk??(HIGH_RISK_ACTIONS.has(input.action)?'high':'normal'),nowIso()); return {id,status:'pending'}; }
export function ensureApprovalRequest(db:DB,input:{policyId:string;employeeId:string;taskId:string;action:string;command?:string;path?:string;risk?:string}):{id:string;status:'pending'} { const existing=db.prepare("SELECT id FROM permission_approval WHERE policy_id=? AND employee_id=? AND task_id=? AND action=? AND COALESCE(command,'')=COALESCE(?,'') AND COALESCE(path,'')=COALESCE(?,'') AND status='pending'").get(input.policyId,input.employeeId,input.taskId,input.action,input.command??null,input.path??null) as {id:string}|undefined;return existing?{id:existing.id,status:'pending'}:requestApproval(db,input); }

export function recordApprovalDecision(db:DB,id:string,input:{decision:'deny'|'allow-once'|'allow-command'|'allow-directory'|'custom-rule';rule?:PermissionRuleInput},options:{resumeTask?:boolean}={}):void { const row=db.prepare('SELECT * FROM permission_approval WHERE id=?').get(id) as {policy_id:string;task_id:string;action:string;command:string|null;path:string|null}|undefined; if(!row) throw new AppError(ErrorCode.NOT_FOUND,`审批请求不存在: ${id}`); if(input.decision==='allow-once') savePermissionRule(db,row.policy_id,{effect:'allow',taskId:row.task_id,action:row.action,commandPattern:row.command?`^${escapeRegex(row.command)}$`:undefined,pathPrefix:row.path??undefined,expiresAt:new Date(Date.now()+60*60_000).toISOString()}); if(input.decision==='allow-command'&&row.command) savePermissionRule(db,row.policy_id,{effect:'allow',action:row.action,commandPattern:`^${escapeRegex(row.command)}$`}); if(input.decision==='allow-directory'&&row.path) savePermissionRule(db,row.policy_id,{effect:'allow',pathPrefix:dirname(row.path)}); if(input.decision==='custom-rule'&&input.rule) savePermissionRule(db,row.policy_id,input.rule); db.prepare('UPDATE permission_approval SET status=?, decision=?, decided_at=? WHERE id=?').run(input.decision==='deny'?'denied':'allowed',input.decision,nowIso(),id);if(input.decision!=='deny'&&(options.resumeTask??true))resumeTaskAfterApproval(db,row.task_id); }
function escapeRegex(value:string):string { return value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'); }
