import type {DB} from '../db/client';
import {AppError,ErrorCode} from '../../shared/errors';
import {nowIso,shortId} from '../../shared/utils';
import {getAgent} from './agent';
import {assertProjectTaskActive,getProjectTask} from './project-task';
import {getProject} from './project';

export type ProjectTaskThreadState='idle'|'running'|'waiting'|'paused'|'failed'|'archived';
export interface ProjectTaskThread{id:string;projectTaskId:string;employeeId:string;executorProfileId:string|null;kind:'primary'|'mirror';rootThreadId:string|null;vendorSessionId:string|null;previousVendorSessionId:string|null;state:ProjectTaskThreadState;health:Record<string,unknown>;handoff:Record<string,unknown>;runCount:number;transcriptBytes:number;compactionCount:number;lastCompactionAt:string|null;createdAt:string;updatedAt:string}
type Row={id:string;project_task_id:string;employee_id:string;executor_profile_id:string|null;kind:'primary'|'mirror';root_thread_id:string|null;vendor_session_id:string|null;previous_vendor_session_id:string|null;state:ProjectTaskThreadState;health_json:string;handoff_json:string;run_count:number;transcript_bytes:number;compaction_count:number;last_compaction_at:string|null;created_at:string;updated_at:string};
const fromRow=(r:Row):ProjectTaskThread=>({id:r.id,projectTaskId:r.project_task_id,employeeId:r.employee_id,executorProfileId:r.executor_profile_id,kind:r.kind,rootThreadId:r.root_thread_id,vendorSessionId:r.vendor_session_id,previousVendorSessionId:r.previous_vendor_session_id,state:r.state,health:JSON.parse(r.health_json),handoff:JSON.parse(r.handoff_json),runCount:r.run_count,transcriptBytes:r.transcript_bytes,compactionCount:r.compaction_count,lastCompactionAt:r.last_compaction_at,createdAt:r.created_at,updatedAt:r.updated_at});
export function getProjectTaskThread(db:DB,id:string):ProjectTaskThread{const row=db.prepare('SELECT * FROM project_task_thread WHERE id=?').get(id) as Row|undefined;if(!row)throw new AppError(ErrorCode.NOT_FOUND,`员工任务线程不存在: ${id}`);return fromRow(row);}
export function listProjectTaskThreads(db:DB,projectTaskId:string):ProjectTaskThread[]{return(db.prepare('SELECT * FROM project_task_thread WHERE project_task_id=? ORDER BY created_at').all(projectTaskId) as Row[]).map(fromRow);}
export function ensureProjectTaskThread(db:DB,input:{projectTaskId:string;employeeId:string;executorProfileId:string|null}):ProjectTaskThread{const projectTask=assertProjectTaskActive(db,input.projectTaskId);const employee=getAgent(db,input.employeeId);const project=getProject(db,projectTask.projectId);if(employee.companyId!==project.companyId)throw new AppError(ErrorCode.UNAUTHORIZED,'员工不属于项目所在公司');const existing=db.prepare("SELECT * FROM project_task_thread WHERE project_task_id=? AND employee_id=? AND kind='primary'").get(input.projectTaskId,input.employeeId) as Row|undefined;if(existing){if(existing.executor_profile_id!==input.executorProfileId)throw new AppError(ErrorCode.CONFLICT,'员工任务线程已绑定其他执行器');return fromRow(existing);}const id=shortId('pth_'),now=nowIso();db.prepare("INSERT INTO project_task_thread (id,project_task_id,employee_id,executor_profile_id,kind,state,created_at,updated_at) VALUES (?,?,?,?,'primary','idle',?,?)").run(id,input.projectTaskId,input.employeeId,input.executorProfileId,now,now);return getProjectTaskThread(db,id);}
export function createProjectTaskMirror(db:DB,input:{projectTaskId:string;employeeId:string;executorProfileId:string|null}):ProjectTaskThread{const root=ensureProjectTaskThread(db,input);const id=shortId('pth_'),now=nowIso();db.prepare("INSERT INTO project_task_thread (id,project_task_id,employee_id,executor_profile_id,kind,root_thread_id,state,created_at,updated_at) VALUES (?,?,?,?,'mirror',?,'idle',?,?)").run(id,input.projectTaskId,input.employeeId,input.executorProfileId,root.id,now,now);return getProjectTaskThread(db,id);}
export function setProjectTaskThreadSession(db:DB,id:string,sessionId:string):ProjectTaskThread{if(!sessionId.trim())throw new AppError(ErrorCode.VALIDATION,'会话 ID 不能为空');db.prepare('UPDATE project_task_thread SET vendor_session_id=?,updated_at=? WHERE id=?').run(sessionId,nowIso(),id);return getProjectTaskThread(db,id);}
export function setProjectTaskThreadState(db:DB,id:string,state:ProjectTaskThreadState):ProjectTaskThread{db.prepare('UPDATE project_task_thread SET state=?,updated_at=? WHERE id=?').run(state,nowIso(),id);return getProjectTaskThread(db,id);}
